# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HistoryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistoryWindow(object):
    def setupUi(self, HistoryWindow):
        HistoryWindow.setObjectName("HistoryWindow")
        HistoryWindow.resize(851, 468)
        HistoryWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(HistoryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 501, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 2px solid black;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 10, 81, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("border: 2px solid black;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(610, 10, 221, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 2px solid black;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(610, 80, 221, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 2px solid black;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 501, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 2px solid black;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 80, 81, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("border: 2px solid black;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(610, 150, 221, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: 2px solid black;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 150, 501, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border: 2px solid black;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(520, 150, 81, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("border: 2px solid black;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(610, 220, 221, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: 2px solid black;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 220, 501, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border: 2px solid black;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(520, 220, 81, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setStyleSheet("border: 2px solid black;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(610, 290, 221, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border: 2px solid black;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 290, 501, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border: 2px solid black;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(520, 290, 81, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("border: 2px solid black;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(610, 360, 221, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border: 2px solid black;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 360, 501, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("border: 2px solid black;")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(520, 360, 81, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(26)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setStyleSheet("border: 2px solid black;")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(470, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 150, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(470, 290, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(470, 360, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(790, 360, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(790, 290, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(790, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(790, 150, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(790, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(790, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color: rgb(245, 236, 180);")
        self.pushButton_12.setObjectName("pushButton_12")
        HistoryWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HistoryWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 20))
        self.menubar.setObjectName("menubar")
        HistoryWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HistoryWindow)
        self.statusbar.setObjectName("statusbar")
        HistoryWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HistoryWindow)
        QtCore.QMetaObject.connectSlotsByName(HistoryWindow)

    def retranslateUi(self, HistoryWindow):
        _translate = QtCore.QCoreApplication.translate
        HistoryWindow.setWindowTitle(_translate("HistoryWindow", "History"))
        self.label.setText(_translate("HistoryWindow", "2+2"))
        self.label_2.setText(_translate("HistoryWindow", "="))
        self.label_3.setText(_translate("HistoryWindow", "4"))
        self.label_4.setText(_translate("HistoryWindow", "568"))
        self.label_5.setText(_translate("HistoryWindow", "2+2+8+10+5+0+5-20x66-2-3...."))
        self.label_6.setText(_translate("HistoryWindow", "="))
        self.label_7.setText(_translate("HistoryWindow", "-160"))
        self.label_8.setText(_translate("HistoryWindow", "40*(-4)"))
        self.label_9.setText(_translate("HistoryWindow", "="))
        self.label_10.setText(_translate("HistoryWindow", "Math Error"))
        self.label_11.setText(_translate("HistoryWindow", "2÷0"))
        self.label_12.setText(_translate("HistoryWindow", "="))
        self.label_13.setText(_translate("HistoryWindow", "..."))
        self.label_14.setText(_translate("HistoryWindow", "..."))
        self.label_15.setText(_translate("HistoryWindow", "="))
        self.label_16.setText(_translate("HistoryWindow", "..."))
        self.label_17.setText(_translate("HistoryWindow", "..."))
        self.label_18.setText(_translate("HistoryWindow", "="))
        self.pushButton.setText(_translate("HistoryWindow", "C"))
        self.pushButton_2.setText(_translate("HistoryWindow", "C"))
        self.pushButton_3.setText(_translate("HistoryWindow", "C"))
        self.pushButton_4.setText(_translate("HistoryWindow", "C"))
        self.pushButton_5.setText(_translate("HistoryWindow", "C"))
        self.pushButton_6.setText(_translate("HistoryWindow", "C"))
        self.pushButton_7.setText(_translate("HistoryWindow", "C"))
        self.pushButton_8.setText(_translate("HistoryWindow", "C"))
        self.pushButton_9.setText(_translate("HistoryWindow", "C"))
        self.pushButton_10.setText(_translate("HistoryWindow", "C"))
        self.pushButton_11.setText(_translate("HistoryWindow", "C"))
        self.pushButton_12.setText(_translate("HistoryWindow", "C"))
