# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newcalc.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from HelpWindov2 import Ui_HelpWindow
from Graph import Ui_GraphWindow
from HistoryWindow import Ui_HistoryWindow
import sys

class Ui_Calculator(object):
        
    def openHelp(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_HelpWindow()        
        self.ui.setupUi(self.window)
        self.window.show()

    def openGraph(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_GraphWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def openHistory(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_HistoryWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    
        

    
        
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(706, 368)
        Calculator.setStyleSheet("\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 661, 61))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"border-width: 3px;\n"
"border: 1px solid black;")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(140, 230, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.button1.setFont(font)
        self.button1.setStyleSheet("background-color: rgb(200, 185, 214);")
        self.button1.setObjectName("button1")
        self.button4 = QtWidgets.QPushButton(self.centralwidget)
        self.button4.setGeometry(QtCore.QRect(140, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.button4.setFont(font)
        self.button4.setStyleSheet("background-color: rgb(200, 185, 214);")
        self.button4.setObjectName("button4")
        self.button7 = QtWidgets.QPushButton(self.centralwidget)
        self.button7.setGeometry(QtCore.QRect(140, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.button7.setFont(font)
        self.button7.setStyleSheet("background-color: rgb(200, 185, 214);\n"
"borde-color: transparent;")
        self.button7.setObjectName("button7")
        self.button8 = QtWidgets.QPushButton(self.centralwidget)
        self.button8.setGeometry(QtCore.QRect(240, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.button8.setFont(font)
        self.button8.setStyleSheet("background-color: rgb(200, 185, 214);")
        self.button8.setObjectName("button8")
        self.button5 = QtWidgets.QPushButton(self.centralwidget)
        self.button5.setGeometry(QtCore.QRect(240, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.button5.setFont(font)
        self.button5.setStyleSheet("background-color: rgb(200, 185, 214);")
        self.button5.setObjectName("button5")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(240, 230, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.button2.setFont(font)
        self.button2.setStyleSheet("background-color: rgb(200, 185, 214);")
        self.button2.setObjectName("button2")
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(340, 230, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.button3.setFont(font)
        self.button3.setStyleSheet("background-color: rgb(200, 185, 214);")
        self.button3.setObjectName("button3")
        self.button6 = QtWidgets.QPushButton(self.centralwidget)
        self.button6.setGeometry(QtCore.QRect(340, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.button6.setFont(font)
        self.button6.setStyleSheet("background-color: rgb(200, 185, 214);")
        self.button6.setObjectName("button6")
        self.button9 = QtWidgets.QPushButton(self.centralwidget)
        self.button9.setGeometry(QtCore.QRect(340, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.button9.setFont(font)
        self.button9.setStyleSheet("background-color: rgb(200, 185, 214);")
        self.button9.setObjectName("button9")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(140, 280, 191, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background-color: rgb(200, 185, 214);")
        self.pushButton_0.setObjectName("pushButton_0")
        self.buttoneq = QtWidgets.QPushButton(self.centralwidget)
        self.buttoneq.setGeometry(QtCore.QRect(450, 280, 231, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(15)
        self.buttoneq.setFont(font)
        self.buttoneq.setStyleSheet("background-color: rgb(103, 105, 255);\n"
"color: rgb(255, 255, 255);")
        self.buttoneq.setObjectName("buttoneq")
        self.buttondel = QtWidgets.QPushButton(self.centralwidget)
        self.buttondel.setGeometry(QtCore.QRect(450, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.buttondel.setFont(font)
        self.buttondel.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttondel.setObjectName("buttondel")
        self.buttonplus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonplus.setGeometry(QtCore.QRect(20, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonplus.setFont(font)
        self.buttonplus.setToolTip("")
        self.buttonplus.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttonplus.setShortcut("")
        self.buttonplus.setObjectName("buttonplus")
        self.buttonsub = QtWidgets.QPushButton(self.centralwidget)
        self.buttonsub.setGeometry(QtCore.QRect(20, 180, 111, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.buttonsub.setFont(font)
        self.buttonsub.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttonsub.setObjectName("buttonsub")
        self.buttonmul = QtWidgets.QPushButton(self.centralwidget)
        self.buttonmul.setGeometry(QtCore.QRect(20, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.buttonmul.setFont(font)
        self.buttonmul.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttonmul.setObjectName("buttonmul")
        self.buttondiv = QtWidgets.QPushButton(self.centralwidget)
        self.buttondiv.setGeometry(QtCore.QRect(20, 230, 111, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.buttondiv.setFont(font)
        self.buttondiv.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttondiv.setObjectName("buttondiv")
        self.buttonpow = QtWidgets.QPushButton(self.centralwidget)
        self.buttonpow.setGeometry(QtCore.QRect(530, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.buttonpow.setFont(font)
        self.buttonpow.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttonpow.setObjectName("buttonpow")
        self.buttonodmocnina = QtWidgets.QPushButton(self.centralwidget)
        self.buttonodmocnina.setGeometry(QtCore.QRect(530, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.buttonodmocnina.setFont(font)
        self.buttonodmocnina.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttonodmocnina.setObjectName("buttonodmocnina")
        self.buttofactorial = QtWidgets.QPushButton(self.centralwidget)
        self.buttofactorial.setGeometry(QtCore.QRect(610, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.buttofactorial.setFont(font)
        self.buttofactorial.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttofactorial.setObjectName("buttofactorial")
        self.buttonsin = QtWidgets.QPushButton(self.centralwidget)
        self.buttonsin.setGeometry(QtCore.QRect(610, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.buttonsin.setFont(font)
        self.buttonsin.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttonsin.setObjectName("buttonsin")
        self.buttonclear = QtWidgets.QPushButton(self.centralwidget)
        self.buttonclear.setGeometry(QtCore.QRect(450, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.buttonclear.setFont(font)
        self.buttonclear.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttonclear.setObjectName("buttonclear")
        self.buttonlb = QtWidgets.QPushButton(self.centralwidget)
        self.buttonlb.setGeometry(QtCore.QRect(450, 80, 31, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.buttonlb.setFont(font)
        self.buttonlb.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttonlb.setObjectName("buttonlb")
        self.buttonrb = QtWidgets.QPushButton(self.centralwidget)
        self.buttonrb.setGeometry(QtCore.QRect(490, 80, 31, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.buttonrb.setFont(font)
        self.buttonrb.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.buttonrb.setObjectName("buttonrb")
        self.pushciarka = QtWidgets.QPushButton(self.centralwidget)
        self.pushciarka.setGeometry(QtCore.QRect(340, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushciarka.setFont(font)
        self.pushciarka.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.pushciarka.setObjectName("pushciarka")
        self.ytaodmocnia = QtWidgets.QPushButton(self.centralwidget)
        self.ytaodmocnia.setEnabled(True)
        self.ytaodmocnia.setGeometry(QtCore.QRect(530, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.ytaodmocnia.setFont(font)
        self.ytaodmocnia.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.ytaodmocnia.setObjectName("ytaodmocnia")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(103, 105, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(530, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 80, 91, 31))
        self.pushButton_6.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(240, 80, 91, 31))
        self.pushButton_7.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(340, 80, 51, 31))
        self.pushButton_8.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(390, 80, 51, 31))
        self.pushButton_9.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 10, 71, 31))
        self.pushButton_10.setStyleSheet("background-color: rgb(223, 255, 162);")
        self.pushButton_10.setObjectName("pushButton_10")
        Calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 706, 20))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 246, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 246, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 246, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 115, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 246, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 246, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 246, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 115, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 246, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 246, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 246, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 115, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.menuHelp.setPalette(palette)
        self.menuHelp.setToolTipsVisible(False)
        self.menuHelp.setObjectName("menuHelp")
        self.menuGraph = QtWidgets.QMenu(self.menubar)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 115, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 115, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 115, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.menuGraph.setPalette(palette)
        self.menuGraph.setObjectName("menuGraph")
        Calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calculator)
        self.statusbar.setObjectName("statusbar")
        Calculator.setStatusBar(self.statusbar)
        self.actionOpen_Manual = QtWidgets.QAction(Calculator)
        self.actionOpen_Manual.setCheckable(False)
        self.actionOpen_Manual.setIconVisibleInMenu(True)
        self.actionOpen_Manual.setObjectName("actionOpen_Manual")
        self.actionOpen_hraph_drawer = QtWidgets.QAction(Calculator)
        self.actionOpen_hraph_drawer.setObjectName("actionOpen_hraph_drawer")
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionOpen_Manual)
        self.menuGraph.addAction(self.actionOpen_hraph_drawer)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuGraph.menuAction())
        
        
        self.pushButton_10.clicked.connect(lambda: self.openHistory())
        self.actionOpen_Manual.triggered.connect(lambda: self.openHelp())
        self.actionOpen_hraph_drawer.triggered.connect(lambda: self.openGraph())
        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.label.setText(_translate("Calculator", ""))
        self.button1.setText(_translate("Calculator", "1"))
        self.button4.setText(_translate("Calculator", "4"))
        self.button7.setText(_translate("Calculator", "7"))
        self.button8.setText(_translate("Calculator", "8"))
        self.button5.setText(_translate("Calculator", "5"))
        self.button2.setText(_translate("Calculator", "2"))
        self.button3.setText(_translate("Calculator", "3"))
        self.button6.setText(_translate("Calculator", "6"))
        self.button9.setText(_translate("Calculator", "9"))
        self.pushButton_0.setText(_translate("Calculator", "0"))
        self.buttoneq.setText(_translate("Calculator", "="))
        self.buttondel.setText(_translate("Calculator", "CE"))
        self.buttonplus.setText(_translate("Calculator", "+"))
        self.buttonsub.setText(_translate("Calculator", "-"))
        self.buttonmul.setText(_translate("Calculator", "x"))
        self.buttondiv.setText(_translate("Calculator", " ÷"))
        self.buttonpow.setText(_translate("Calculator", "xʸ"))
        self.buttonodmocnina.setText(_translate("Calculator", "√x"))
        self.buttofactorial.setText(_translate("Calculator", "x!"))
        self.buttonsin.setText(_translate("Calculator", "sin(x)"))
        self.buttonclear.setText(_translate("Calculator", "AC"))
        self.buttonlb.setText(_translate("Calculator", "("))
        self.buttonrb.setText(_translate("Calculator", ")"))
        self.pushciarka.setText(_translate("Calculator", "."))
        self.ytaodmocnia.setText(_translate("Calculator", "ʸ√x"))
        self.pushButton.setText(_translate("Calculator", "ANS"))
        self.pushButton_3.setText(_translate("Calculator", "tan(x)"))
        self.pushButton_4.setText(_translate("Calculator", "log"))
        self.pushButton_2.setText(_translate("Calculator", "cos(x)"))
        self.pushButton_5.setText(_translate("Calculator", "%"))
        self.pushButton_6.setText(_translate("Calculator", "π "))
        self.pushButton_7.setText(_translate("Calculator", "e"))
        self.pushButton_8.setText(_translate("Calculator", "RAD"))
        self.pushButton_9.setText(_translate("Calculator", "DEG"))
        self.pushButton_10.setText(_translate("Calculator", "History"))
        self.menuHelp.setTitle(_translate("Calculator", "Help"))
        self.menuGraph.setTitle(_translate("Calculator", "Graph"))
        self.actionOpen_Manual.setText(_translate("Calculator", "Open Manual"))
        self.actionOpen_Manual.setStatusTip(_translate("Calculator", "Manual"))
        self.actionOpen_Manual.setShortcut(_translate("Calculator", "Ctrl+M"))
        self.actionOpen_hraph_drawer.setText(_translate("Calculator", "Open graph drawer"))
        self.actionOpen_hraph_drawer.setStatusTip(_translate("Calculator", "Graph"))
        self.actionOpen_hraph_drawer.setShortcut(_translate("Calculator", "Ctrl+G"))
#import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())